development:
  adapter: postgresql
  encoding: unicode
  database: udo_development
  pool: 5
  username: postgresql
  password: postgresql

test:
  adapter: postgresql
  encoding: unicode
  database: udo_test
  pool: 5
  username: postgresql
  password: postgresql
